version: '3'

services:

  frontend:
    container_name: frontend_app

    build: ./

    volumes: 
      - ./:/app

    ports: 
      - "8080:8080"

    networks:
      - connection
    
  backend:
    container_name: backend

    depends_on:
      - db

    links:
      - db

    restart: on-failure

    build:
      context: backend/

    ports:
      - "3030:3030"

    networks:
      - connection

  db:
    image: mysql:5.7

    container_name: db

    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root' 
      MYSQL_DATABASE: 'portfolio'

    ports:
      - '3307:3306'
    
    networks:
      - connection

networks:
  connection:
    driver: bridge